[project]
name = "borgstore"
dynamic = ["version"]
authors = [{name="Thomas Waldmann", email="tw@waldmann-edv.de"}, ]
description = "key/value store"
readme = "README.rst"
keywords = ["kv", "key/value", "store"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
license = {text="BSD"}
requires-python = ">=3.9"
dependencies = [
    "cryptography < 43.0.0",  # using a more recent version triggers annoying warnings with paramiko
    "paramiko",
]

[project.urls]
Homepage = "https://github.com/borgbackup/borgstore"

[build-system]
requires = ["setuptools", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# make sure we have the same versioning scheme with all setuptools_scm versions, to avoid different autogenerated files
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1015052
# https://github.com/borgbackup/borg/issues/6875
write_to = "src/borgstore/_version.py"
write_to_template = "__version__ = version = {version!r}\n"

[tool.black]
line-length = 120
skip-magic-trailing-comma = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.flake8]
# Ignoring E203 due to https://github.com/PyCQA/pycodestyle/issues/373
ignore = ['E226', 'W503', 'E203']
max_line_length = 120
exclude = ['build', 'dist', '.git', '.idea', '.mypy_cache', '.tox']

[tool.mypy]
python_version = '3.10'
strict_optional = false
local_partial_types = true
show_error_codes = true
files = 'src/borgstore/**/*.py'
